### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by paurosello** [k8spin/k8spin-operator#2]
### Description
Network configuration is a core concept at K8Spin. In our past SaaS offering, all Spaces/Namespaces where isolated in the cluster meaning that a pod in a specific namespace couldn't request a pod in a different namespace.
We want more options in this Operator

### Propssal

What we need in this operator is some kind of networking pre-configurations:

- Fully isolated
- Enable between all Spaces in the same Tenant
- Enable between all Spaces in the same Organization

#### Before

```
apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: dev
spec:
  resources:
    cpu: "2"
    memory: "1G"
  roles:
    - name: space-admin # Cluster Role
      groups: ["K8Spin.cloud"] # User Certificate O=
    - name: space-viewer # Cluster Role
      users: ["Angel", "Pau"] # User Certificate CN=
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 64Mi
```

#### After

```
apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: dev
spec:
  networking: isolated
  resources:
    cpu: "2"
    memory: "1G"
  roles:
    - name: space-admin # Cluster Role
      groups: ["K8Spin.cloud"] # User Certificate O=
    - name: space-viewer # Cluster Role
      users: ["Angel", "Pau"] # User Certificate CN=
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 64Mi
```

#### Expected output

Once a new space is created, it has to have a network policy according with the value configured in the Space.spec.networking attribute. The default behaviour should be isolated.
