### ISSUE TITLE
kubectl install not working

### ISSUE THREAD

**Issue by Rhiod** [k8spin/k8spin-operator#29]
### What are the steps to reproduce this issue?
1. Install operator with kubectl

### What happens?
Docker image v1.0.3 does not exist in docker hub

### What were you expecting to happen?
Image must be available in the registry

### Any logs, error output, etc?
Failed to pull image "k8spin/k8spin-operator:v1.0.3": rpc error: code = Unknown desc = Error response from daemon: manifest for k8spin/k8spin-operator:v1.0.3 not found: manifest unknown: manifest unknown

### Any other comments?
…

### What versions of the software are you using?
----------------------------------------
**Operating System:** Ubuntu 18.04

**Docker Version:** 19.03.13

**kubectl Version:** GitVersion:"v1.18.9+k3s1"

**Comment by angelbarrera92** [comment]
Hi @Rhiod, thanks for spotting this bug.

We are pushing a new patch release with the helm chart default values properly configured. Meanwhile, you can set the proper image version in your values.yaml file:

```yaml
k8spin_operator:
  image:
    name: ghcr.io/k8spin/k8spin-operator # k8spin-operator image name
    tag: v1.0.3
k8spin_webhook:
  image:
    name: ghcr.io/k8spin/k8spin-webhook # k8spin-webhook image name
    tag: v1.0.3
```

I'll ping you once the new release v1.0.4 becomes available
